export type EmployeeDataForEdit = {
    employee_number: string;
    first_name: string;
    last_name: string;
    other_names?: string | null;
    email?: string | null;
    phone: string;
    id_type: string;
    id_number: string;
    kra_pin: string;
    shif_number?: string | null;
    nssf_number?: string | null;
    date_of_birth: Date | undefined;
    gender: string;
    marital_status?: string | null;
    citizenship?: string | null;
    has_disability?: boolean | null; // Allow null for boolean from backend
    date_joined: Date | undefined;
    job_title?: string | null;
    department?: string | null;
    job_type: string;
    employee_status: string;
    employee_status_effective_date?: Date | undefined;
    end_of_probation_date?: Date | undefined;
    contract_start_date?: Date | undefined;
    contract_end_date?: Date | undefined;
    termination_date?: Date | undefined;
    termination_reason?: string | null;
    basic_salary: number;
    salary_effective_date?: Date | undefined;
    payment_method: string;
    bank_name?: string | null;
    bank_branch?: string | null;
    bank_code?: string | null;
    bank_account_number?: string | null;
    mpesa_phone_number?: string | null;
    is_helb_paying?: boolean | null;
    benefits?: boolean | null;
    extra_deductions?: boolean | null;
    paye_tax_exemption?: boolean | null;
    disability_tax_exemption?: boolean | null;
    physical_address?: string | null;
    postal_address?: string | null;
    county?: string | null;
    postal_code?: string | null;
    next_of_kin_name?: string | null;
    next_of_kin_relationship?: string | null;
    next_of_kin_phone?: string | null;
}